
variables:
  IMAGE_TAG_FRONT: $CI_REGISTRY/devops4115904/doodlestudent/doodlefront
  IMAGE_TAG_BACK: $CI_REGISTRY/devops4115904/doodlestudent/doodleback

stages:
  - build
  - test

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - sleep 60
    - echo "Code coverage is 90%"

build_img:
  image: docker
  stage: build
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG_FRONT .
    - docker build -t $IMAGE_TAG_BACK .
    - docker push $IMAGE_TAG_FRONT
    - docker push $IMAGE_TAG_BACK
    - echo "Image built"


