
stages:
  - build
  - test

unit-test-job:   # This job runs in the test
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - sleep 60
    - echo "Code coverage is 90%"

build_img:
  image: docker
  stage: build
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/devops4115904/doodlestudent/front/doodlefront
    - docker push $CI_REGISTRY/devops4115904/doodlestudent/front/doodlefront
    - echo "Image built"


