apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    fr.doodle.service: back
  name: back
  namespace: doodle
spec:
  replicas: 1
  selector:
    matchLabels:
      fr.doodle.service: back
  template:
    metadata:
      labels:
        fr.doodle.service: back
    spec:
      containers:
          env:
            - name: MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED
              value: "true"
          image: registry.gitlab.com/devops4115904/doodlestudent/doodleback:latest
          name: back
          ports:
            - containerPort: 8080
      restartPolicy: Always
      imagePullSecrets:
        - name: doodle-app-secret