version: "3.8"
services:
  etherpad:
    image: etherpad/etherpad:1.8
    ports:
      - "9001:9001"
    volumes:
      - ./APIKEY.txt:/opt/etherpad-lite/APIKEY.txt
    environment:
      - ETHERPAD_API_KEY=your_etherpad_api_key_here
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${API_PORT}:8080"
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=${QUARKUS_DATASOURCE_JDBC_URL}
      - QUARKUS_DATASOURCE_USERNAME=${QUARKUS_DATASOURCE_USERNAME}
      - QUARKUS_DATASOURCE_PASSWORD=${QUARKUS_DATASOURCE_PASSWORD}
      - QUARKUS_MAILER_HOST=${QUARKUS_MAILER_HOST}
      - QUARKUS_MAILER_PORT=${QUARKUS_MAILER_PORT}
      - QUARKUS_MAILER_USERNAME=${QUARKUS_MAILER_USERNAME}
      - QUARKUS_MAILER_PASSWORD=${QUARKUS_MAILER_PASSWORD}
      - QUARKUS_MAILER_FROM=${QUARKUS_MAILER_FROM}
      - DOODLE_INTERNAL_PAD_URL=${ETHERPAD_INTERNAL_URL}
      - DOODLE_EXTERNAL_PAD_URL=${ETHERPAD_EXTERNAL_URL}
    depends_on:
      etherpad:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/q/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s 