version: "3.8"
services:
  db:
    image: mysql
    volumes:
      - ./src/main/resources/db/migration/:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tlc
      - MYSQL_USER=
      - MYSQL_PASSWORD=
  etherpad:
    image: etherpad/etherpad:1.8
#    ports:
#      - "9001:9001"
    volumes:
      - ./APIKEY.txt:/opt/etherpad-lite/APIKEY.txt
  mail:
    image: bytemark/smtp
    restart: always
    ports:
      - "2525:25"
  api:
    container_name: api
    image: doodleback
    command: ["java","-jar","target/tlcdemoApp-1.0.0-SNAPSHOT.jar","-Dquarkus.datasource.username=tlc","-Dquarkus.datasource.password=tlc","-Dquarkus.datasource.jdbc.url=jdbc:mysql://db:3306/tlc?useUnicode=true&serverTimezone=Europe/Paris","-Ddoodle.internalPadUrl=http://etherpad:9001","-Ddooble.externalPadUrl=http://pad.tlc.fr:90/"]
    restart: always
  
  front:
    container_name: front
    image: doodlefront
    ports:
      - 90:80
    volumes:
      - ./exampleconf/doodle.conf:/etc/nginx/conf.d/doodle.conf
      - ./exampleconf/myadmin.conf:/etc/nginx/conf.d/myadmin.conf
      - ./exampleconf/pad.conf:/etc/nginx/conf.d/pad.conf
  
  myadmin:
    image: phpmyadmin
    container_name: myadmin
    environment:
      - PMA_HOST=db

