version: "3.8"
services:
  db:
    image: mysql
    volumes:
      - ./src/main/resources/db/migration/:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tlc
      - MYSQL_USER=
      - MYSQL_PASSWORD=
  etherpad:
    image: etherpad/etherpad:1.8
#    ports:
#      - "9001:9001"
    volumes:
      - ./APIKEY.txt:/opt/etherpad-lite/APIKEY.txt
  mail:
    image: bytemark/smtp
    restart: always
    ports:
      - "2525:25"
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db
      - etherpad
      - mail
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/q/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
  
  front:
    container_name: front
    build:
      context: ../front
      dockerfile: Dockerfile
    ports:
      - 90:80
    volumes:
      - ./exampleconf/doodle.conf:/etc/nginx/conf.d/doodle.conf
      - ./exampleconf/myadmin.conf:/etc/nginx/conf.d/myadmin.conf
      - ./exampleconf/pad.conf:/etc/nginx/conf.d/pad.conf
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
  
  myadmin:
    image: phpmyadmin
    container_name: myadmin
    environment:
      - PMA_HOST=db

