name: Main CI/CD Pipeline

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]
  workflow_dispatch:

jobs:
  # ==========================================
  # Job: Determine what to build
  # ==========================================
  changes:
    name: Determine Changes
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check for changes
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            frontend:
              - 'front/**'
            backend:
              - 'api/**'

  # ==========================================
  # Job: Frontend CI/CD (reusable workflow)
  # ==========================================
  frontend:
    name: Frontend CI/CD
    needs: changes
    if: needs.changes.outputs.frontend == 'true'
    uses: ./.github/workflows/frontend-ci-cd.yml
    with: {}

  # ==========================================
  # Job: Backend CI/CD (reusable workflow)
  # ==========================================
  backend:
    name: Backend CI/CD
    needs: changes
    if: needs.changes.outputs.backend == 'true'
    uses: ./.github/workflows/backend-ci-cd.yml
    with: {}

  # ==========================================
  # Job: Full Stack Deploy Summary (only on main)
  # ==========================================
  full-deploy-summary:
    name: Full Stack Deploy Summary
    runs-on: ubuntu-latest
    needs: [changes, frontend, backend]
    if: |
      github.ref == 'refs/heads/main' && 
      (needs.changes.outputs.frontend == 'true' || needs.changes.outputs.backend == 'true')
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploy Summary
        run: |
          echo "🚀 Deployment Summary"
          echo "===================="
          echo "Frontend changes: ${{ needs.changes.outputs.frontend }}"
          echo "Backend changes: ${{ needs.changes.outputs.backend }}"
          echo "Deployment completed successfully!"
      - name: Notify deployment
        run: |
          echo "✅ Full stack deployment completed!"
          echo "Frontend: https://your-vercel-app.vercel.app"
          echo "Backend: https://api-doodle-h2fya8esf7e8bpd8.canadacentral-01.azurewebsites.net"
